### ISSUE TITLE
doesn't work?

### ISSUE THREAD

**Issue by stasbel** [modal-labs/synchronicity#115]
this:

```python
import synchronicity

synchronizer = synchronicity.Synchronizer()

@synchronizer.create_blocking
async def f(x):
   await asyncio.sleep(1.0)
   return x ** 2

async def g():
   return await f(42)

import asyncio

asyncio.run(g())
```

gives me: `TypeError: object int can't be used in 'await' expression`
as expected :)

**Comment by erikbern** [comment]
right because `f(42)` evaluates to 1764 and then you're trying to await 1764 – `f` will be a blocking function with this decorator

so this is intended behavior afaict.

does that make sense?

**Comment by stasbel** [comment]
this is of course totally makes sense
but then, how does the example from README.md makes sense? 
please explain how should `f in an asynchronous context works the normal way`
sorry, I might not get an obvious thing here

**Comment by stasbel** [comment]
I ended up using `f.aio` every time I want to await it inside async func
cool lib btw :)

**Comment by erikbern** [comment]
> please explain how should `f in an asynchronous context works the normal way`

I think the docs are outdated – an earlier version of synchronicity would try to infer the context and change the behavior automatically. I'll change the docs, thanks!
